clc;
clear functions;

old_dir = cd(fileparts(which(mfilename)));

[~,mexLoaded] = inmem('-completenames');
eval('while mislocked(''ipopt''); munlock(''ipopt''); end;');

disp('---------------------------------------------------------');
CMD = 'mex -largeArrayDims -Isrc ';

if ismac
  IPOPT_HOME = '../work/coinbrew/dist';
  CMD = [ CMD ...
    '-I/usr/local/include/coin ' ...
    '-I' IPOPT_HOME '/include/coin-or ' ...    
    '-output bin/osx/ipopt_osx ' ...
    '-Lbin/osx -L/usr/local/lib -lipopt ' ...
    'CXXFLAGS=''$CXXFLAGS -Wall -O2 -g'' ' ...
  ];
elseif isunix
  IPOPT_HOME = '../work/coinbrew/dist';
  CMD = [ CMD ...
    '-I' IPOPT_HOME '/include/coin-or ' ...
    '-output bin/linux/ipopt_linux ' ...
    'CXXFLAGS=''$CXXFLAGS -Wall -O2 -g'' ' ...
    'LDFLAGS=''$LDFLAGS -static-libgcc -static-libstdc++'' ' ...
    'LINKLIBS=''-Lbin/linux -L$MATLABROOT/bin/$ARCH -Wl,-rpath,$MATLABROOT/bin/$ARCH -lipopt -lcoinmumps -lgfortran -llapack -lblas -ldl -lMatlabDataArray -lmx -lmex -lmat -lm '' ' ...
  ];
elseif ispc
  IPOPT_HOME = '../Ipopt-3.13.2-win64-msvs2019-md';
  CMD = [ CMD ...
    '-I' IPOPT_HOME '/include/coin-or ' ...
    '-output bin/windows/ipopt_win ' ...
    IPOPT_HOME '/lib/ipopt.dll.lib ' ...
  ];
else
  error('architecture not supported');
end

CMD = [ CMD, './src/ipopt.cc ./src/IpoptInterfaceCommon.cc ' ];

disp(CMD);
eval(CMD);

cd(old_dir);

disp('----------------------- DONE ----------------------------');
